### ISSUE TITLE
Exception: batching error - examples do not produce identical results under batching

### ISSUE THREAD

**Issue by linamy85** [kelvinguu/neural-editor#11]
Hello,
Thank you for releasing such an amazing work. I've tried to run the process by following steps.

1. Clone this repo
2. `mkdir -p $DATA_DIR` and uncompressed Glove vectors into `$DATA_DIR/word_vectors`
3.  Download `glove.6B.300d_onebil.txt` and `glove.6B.300d_yelp.txt` from https://worksheets.codalab.org/bundles/0x89bc0497bbb14ee489d33e032fa43a2e/
4. Download onebillion_split dataset from https://worksheets.codalab.org/bundles/0x017b7af92956458abc7f4169830a6537/ and put them in `$DATA_DIR/onebillion_split`

However, I received an error while executing `python textmorph/edit_model/main.py configs/edit_model/edit_onebil.txt --gpu 0` within docker

> individually:
Variable containing:
 205.0143
[torch.cuda.FloatTensor of size 1 (GPU 0)]
> 
> batched:
Variable containing:
 205.0143
[torch.cuda.FloatTensor of size 1 (GPU 0)]
>
> Traceback (most recent call last):
  File "textmorph/edit_model/main.py", line 40, in <module>
    exp.train()
  File "/code/textmorph/edit_model/training_run.py", line 265, in train
    self._train(self.config, self._train_state, self._examples, self.workspace, self.metadata, self.tb_logger)
  File "/code/textmorph/edit_model/training_run.py", line 399, in _train
    editor.test_batch(noiser(train_batches[0]))
  File "/code/textmorph/edit_model/editor.py", line 128, in test_batch
    raise Exception('batching error - examples do not produce identical results under batching')
Exception: batching error - examples do not produce identical results under batching

After some checks, I found the `individually` is 205.01431 while `batched` is 205.01433, what should I do with this?

Appreciate any help! Thank you :smile:

**Comment by jdxyw** [comment]
have the same issue
