### ISSUE TITLE
glove.6B.300d_onebil.txt file not found error

### ISSUE THREAD

**Issue by yamsgithub** [kelvinguu/neural-editor#14]
I followed the instructions in https://github.com/kelvinguu/neural-editor/tree/readme. But I get the following error when executing: 

> python textmorph/edit_model/main.py configs/edit_model/edit_onebil.txt

The glove.6B.zip does not have this file. How do I obtain it?

No checkpoint to reload. Initializing fresh.
Traceback (most recent call last):
  File "textmorph/edit_model/main.py", line 32, in <module>
    exp = experiments.new(config)  # new experiment from config
  File "/code/gtd/ml/training_run.py", line 144, in new
    run = self._run_factory(config, save_dir)
  File "/code/textmorph/edit_model/training_run.py", line 255, in __init__
    self._train_state = self._initialize_train_state(config)
  File "/code/textmorph/edit_model/training_run.py", line 322, in _initialize_train_state
    editor = cls._build_editor(config.editor)
  File "/code/textmorph/edit_model/training_run.py", line 297, in _build_editor
    word_embeddings = SimpleEmbeddings.from_file(file_path, config.word_dim, vocab_size=config.vocab_size)
  File "/code/gtd/ml/vocab.py", line 184, in from_file
    with codecs.open(file_path, 'r', encoding='utf-8') as f:
  File "/opt/conda/envs/pytorch-py27/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '/data/word_vectors/glove.6B.300d_onebil.txt'

**Comment by adempsey** [comment]
@yamsgithub I believe the other word vectors are located here: https://worksheets.codalab.org/bundles/0x89bc0497bbb14ee489d33e032fa43a2e/

See #6

**Comment by yamsgithub** [comment]
@adempsey Thanks!
